### PR TITLE
Added a shortcut for UIACollectionCell and another for UIATableCell.

### PR DESCRIPTION
**Pull request by hs025828**
I added a shortcut to retrive UIACollectionCell's. There is currently no way of searching for collection cells by tag. In order to retrive just collection cells without this patch, you'd have to search using a wild card \* and then filter the results yourself.

I also added an alternative shortcut for retrieving tableview cells. I did this because it seemed logical to have a shortcut named tableCell since there is now one named collectionCell. The current tablecell shortcut, which is just "cell", seemed ambiguous. Despite the ambiguity, I left the old shortcut to keep the change passive. What do you think?

### CODE REVIEW

**Comment by bootstraponline** [comment]
:+1:

**Comment by hs025828** [comment]
I fudged up.  You can't search for tablecells with the syntax I first submitted.  You need to have only one 'UIATableCell' in the list.  I've updated the pull request.  I'll need to update the one submitted to appium.

**Comment by jaykz52** [comment]
Cool. Will take a look tonight or tomorrow.

**Comment by jaykz52** [comment]
@kinghenry3 can you rebase/merge with latest? I'll get this merged into master ASAP after that. Thanks!

**Comment by hs025828** [comment]
Done.

**Comment by bootstraponline** [comment]
Thanks!

**Pull request merged**
